development:
  adapter: postgresql
  database: shortener_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: shortener_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: shortener_production
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
